#+STYLE: <link rel="stylesheet" type="text/css" href="css/worg.css" />
#+TITLE: О проекте
#+AUTHOR: Urist McLisper
#+EMAIL: mclisper@gmail.com

* Что это за проект?
DF - выдающийся проект с безумным уровнем детализации игрового
мира. Нам это очень нравится. Мы прекрасно понимаем, что одному с
чистого листа поднимать такой проект - очень не просто, особенно, если
это хобби, а не основная работа (как у Тоади, например).


Этот проект - попытка собрать и упорядочить достаточно большой объем
информации по "предметной области" игрового мира, который нам всем так
нравится. Этот проект - попытка облегчить жизнь тому самому одинокому
разработчику, который мечтает о своем DF.

* Чего мы хотим?
#+BEGIN_QUOTE
Напишу сумбурно что я думаю по всему этому поводу. Мысли запиливать 
свой ДФ, я уверен возникали у многих и всплески подобных настроений 
бывают обычно после каких-то успехов (даже не совсем крупных) 
одиночек, который пилят что-то своё и показывают, и обсуждают на борде 
(слания, например), но в процесс разработки никого допускать не 
собираются (причины опустим). Так к чему я это все клоню? А к тому, 
что тут есть (мало, но есть; как известно - люди подключаются 
активней, когда есть какие-то результаты) люди, который хотят запилить 
что-то в духе ДФ, но не могут по ряду причин. Что я предлагаю? Итак, 
господа хорошие, если мы не можем написать программу, то может 
попробуем хотя бы спроектировать ее? В общем и целом пласт технологий, 
алгоритмов, фич, правил и условий будет един - эту часть мы вполне 
можем делать коллективно и децентрализованно. Я предлагаю организовать 
подробную базу знаний/ТЗ где была бы собранна ценная информация для 
разработчика. И держать всю эту инфу на гитхабе, например - можно и не 
пушить свои изменения, добавления в чужие репы - кому надо тот и сам 
заберет (а забирать коммиты у всех права есть). Таким образом 
обеспечена децентрализованность и отсутствие проблем с правами доступа 
(свн - овнеры, контрибьютеры, коммитеры; плюс все хранится 
централизовано - велика вероятность все проебать; децентрализованные 
системы - надежнее, тут и спору нет). 

Что должно быть в этой базе знаний? Я на первый взгляд разбил бы эту 
инфу на следующие категории: 
- общая информация, не привязанная к реализации 
  - общие ожидания от игры, вишлисты, фичреквесты - фантазировать
    здесь. Тут тусуются самые безрукие.
  - описание предметных областей - что-то вроде инфы из магмавики. Тут
    ценится навык подробно описать и разжевать какие-то концепции (биомы, конвеер производства и другое). 
  - алгоритмы - тщательно описанные и разжеванные (поиск путей, жидкости, генераторы шумов и прочее). 
- информация привязанная к реализации 
  - структуры данных, форматы 
  - реализации алгоритмов 
- Другое - какие-то полезные статьи и инфа. 
#+END_QUOTE
* Кто мы?
Одинокие разработчики, которые в глубине души мечтают сделать свой DF.
* Название проекта
Я пока недалеко продвинулся в дварфийском, но по D&D'шной версии
"undivver arau" переводится как "большой план/стратегия".
