#+STYLE: <link rel="stylesheet" type="text/css" href="css/worg.css" />
#+TITLE: roadmap
#+AUTHOR: Urist McLisper
#+EMAIL: mclisper@gmail.com

Пока что здесь находится roadmap неизвестных (в /df/ кто-то постил
это), не с целью нагло копировать, а с целью аккумулировать полезный
опыт, не забыть про какие-то аспекты, моменты, фичи.


Своего roadmap'а пока что нету, все находится в зачаточном состоянии.

* ROADMAP из =/df/=
Вся разработка ведётся открытым способом в публичном репозитории (гитхаб, гуглокод или типа того). 
Между каждым официальным выпуском совершаются десятки и сотни коммитов. Присвоение номера и выпуск (с постиками в бложеках и на бордочках) осуществляются когда все перечисленные условия выполнены. Какие-то подсистемы могут развиваться быстрее остальных и опережать график, в таких случаях релиз всё равно будет ждать отстающих. 

** версия 0.1 
1. мир 100x100x100 тайлов 
2. целиком в памяти 
3. три вида минералов 
4. если парсер равок готов - пусть будет и минералы берутся из него, иначе аккуратно захардкодим их до поры. 
5. примитивный генератор мира (генерим карту высот, заливаем всё первым минералом, местами делаем вкрапления второго и третьего минерала)
6. мир как-то можно смотреть 

** версия 0.2 
1. в мир вводится понятие "кадра" или "тика" 
2. жидкости текут 
3. мир генерируется более-менее интересно (но без городов, русел рек и т.п., просто зайчатки геологии) 
4. парсер равок, по возможности всякие параметры берутся через него 
5. редактор карт (без него сложно отлаживать жидкости) 
6. первые структуры (стены) 
7. Начинается генератор цивилизаций и городов 

** версия 0.3 
1. хороший, годный парсер равок, всё берётся из него, включая вязкость жидкостей 
2. первые существа 
3. генератор мира окончательно становится процедурным, отпадает нужда хранить все тайлы. Мир становится большим. 
4. загружается и играется только часть мира 
5. Жидкости хорошо текут, работают сообщающиеся сосуды. Как-то надо решить вопрос с реками, текущими за пределы загруженной области. Можно как в df, можно (если получится) более честно обсчитывать ток рек (сделал плотину @ город в ста верстах ниже по течению вымер от жажды). 

** версия 0.4 
1. Первые прототипы клиентского кода. Ещё без сети, но уже со строгой изоляцией от потрохов игровой логики, с ограниченной видимостью и, конечно, с возможностью управления существом (пока только одним). Графон - какой получится: текст, от стоунсенса, от майнтеста, от Quake 4. Лишь бы было. 
2. ИИ существ. Лучше начать со случая "охотник-жертва". 
3. Ведётся работа над генератором мира (геология, реки, селения), на совместимость сейвов кладётся болт. 
4. есть какие-то существа, которых можно осмысленно поселить в города. 
5. органы существ, ранения 
6. вводим разные материалы 
7. вводим понятие температуры, эффекты горения, плавления и т.д. 
8. примитивная боёвка 
9. мультитайловые структуры (типа мастерских) 
10. структуры, способные менять прозрачность и проходимость (иными словами, ворота и подъёмные мосты). Корректная работа поля зрения игрока и течения жидкостей. 

** версия 0.5 
1. Сетевая подсистема, первые попытки игры >1 игрока в одном мире 
2. Предметы. Одежда (надета), инструменты (в руках и прочих подходящих конечностях), хлам на земле. 
3. Создаётся "дварфийский хайвмайнд", игрок может отдавать какие-то приказы, а входящие в хайвмайнд существа будут их выполнять, их ИИ должен быть соответствующим образом доработан. 
4. Если заглянуть в город - кто-то там должен суетиться и как-то изображать жизнь. 
5. система органов поддерживает создание форготни и НЁХ и вся эта херня логично живёт и убивается. 
6. Улучшения по всем направлениям: генератор мира, ИИ, физика, биология, больше равок. 
8. развитая боёвка 
9. баллистика (не только ядра, но и отрубленные конечности) 
10. обрушения конструкций. Сопромат, все дела. 

** версия 0.6 
1. игра в режиме крепости по сети (не обязательно должно быть интересно и комфортно, но должно технически работать). 
2. Ещё больше всяких ништяков. 
3. боёвка не хуже, чем в df 
4. Улучшения по всем направлениям 
5. Генератор цивилизаций порождает всяких королей-личей, Подземелья С Эпичными Названиями, легенды и биографии. 

** версия 1.0 
1. Сингловый режим крепости дворфов полноценен и играбелен, хотя и не такой насыщенный всякой всячиной, как в df. Есть нобли, армия, дворфы жрут, пьют, радуются, злятся, работают, рожают детей и умирают. 
2. Существа знают легенды и помнят важные события, свидетелями которых были. 
3. Мультиплеер в статусе "экспериментально". Если удастся решить геймплейные дилеммы типа "Вася хочет поставить на паузу, а Петя - промотать пару сезонов", то хорошо. Иначе - без паузы или с глобальной паузой. 

** версия 1.1 
1. больше фич 
2. Мультиплеер готов и рекомендован к использованию. 

** версия 1.2 
1. Нью-васюки становятся мировой шахматной столицей, открывается международный аэропорт.
